- name: Install Nvm
  shell: |
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v{{ nvm.version }}/install.sh | sh
  args:
    creates: /home/fedora/.nvm/nvm.sh
  become_user: fedora
- name: Install NodeJS
  shell: |
    source /home/fedora/.nvm/nvm.sh
    nvm install 8
    nvm use 8
  become_user: fedora
- name: Install Angular CLI
  shell: |
    source /home/fedora/.nvm/nvm.sh
    npm install -g @angular/cli
  become_user: fedora
